name: Reusable Workflow
on:
  workflow_call:
    inputs:
      artifact-name:
        description: "Name of the artifact to download"
        required: true
        default: dist
        type: string
    # secrets:
    #   some-secret:
    #     required: false
    outputs:
      result:
        description: "Result of the deployment"
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v6
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output message
        run: echo 'Deploying application...'
      - name: Set result output
        id: result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
